PrestaShopCorp/docs.cloud.prestashop.com

- docs/src/.vuepress/config.js
- docs/src/3-prestashop-account/README.md
- netlify.toml
Based on Dimitri, Agathe and Elie's testing
> Reworked the PS Account integration backend part

- docs/src/3-prestashop-account/README.md
> New procedure for PS Account integration

- docs/src/.vuepress/config.js
- docs/src/0-introduction/README.md
- docs/src/2-preparing-your-environment/README.md
- docs/src/3-prestashop-account/README.md
- docs/src/4-account-and-billing/README.md
Added an explanation about window.psaccountsVue.isOnboardingCompleted() (awaiting PHP solution)
Added a note about soon deprecated VueJS integration
Removed Design System
> Implementing feedback

- docs/src/7-faq/README.md
> Remove question about VueJS and other frameworks

- docs/src/4-prestashop-billing/README.md
- docs/src/7-faq/README.md
Inverse condition to display billing component only when account is associated
> Doc feedback

- docs/src/7-faq/README.md
Replace SaaS App by PrestaShop Integration Framework
> Replace SaaS App by PrestaShop Integration Framework

- docs/src/1-how-it-works/README.md
A small fix for the CloudSync API doc link
> Update Doc - CloudSync APIs doc link is broken

- docs/src/4-prestashop-account/README.md
- docs/src/5-prestashop-billing/README.md
- docs/src/7-prestashop-cloudsync/README.md
- Add compatibility limit to avoid error on PHP 7.2 due to PSR.
- Fix some actions names
- Fix some text color
- Remove unwanted code in Cloud Sync (itneverworks)
> Add compatibility limit

- docs/src/9-submitting-your-module/README.md
Add a block before the module submission to remind tech vendors to pay attention to the Billing live mode
> Add Billing warning Sandox mode

- docs/src/8-apis/README.md
Added link to the Postman collection of the Raw API
> Expose RAW API Postman Collection link

- docs/src/.vuepress/config.js
- docs/src/13-UI-Kit/badge/README.md
> Puik documentation : add badge

- docs/src/.vuepress/config.js
- docs/src/13-UI-Kit/accordion/accordion.md
> Puik documentation : add accordion

- docs/src/5-prestashop-billing/README.md
Removed an extra space in the partnerLogo url
> Update logo url

- docs/src/.vuepress/config.js
- docs/src/13-UI-Kit/tooltip/README.md
> PUIK documentation: tooltip

- docs/src/7-prestashop-cloudsync/README.md
Adding Stocks and Stores to the shop consents.
> Adding new shop consent to the CloudSync CDC

- docs/src/10-validation-checklist/README.md
Add Smarty variable block
Add if not defined block
Add htaccess block
> Update Validation Checklist

- docs/src/12-legacy-account-and-billing/README.md
- docs/src/4-prestashop-account/README.md
- docs/src/7-prestashop-cloudsync/README.md
Adding autoload.php in module class for OS version of PrestaShop + fix internal links
> [IMP] Adding autoload.php in module class for OS version of PS

- docs/src/5-prestashop-billing/4-how-tos/4-handle-plan-selection/README.md
Correction on function's name and block's name.
> Update JS for custom plan

- docs/src/7-prestashop-cloudsync/README.md
Adding manufacturers and suppliers concent in the CDC listing.
> Update CloudSync Shop Consents listing

- docs/src/5-prestashop-billing/4-how-tos/4-handle-plan-selection/README.md
use added componentGroupId in order to assign
title and feature to custom plan
> docs(OFF-990): new implementation for custom plan

- docs/src/10-validation-checklist/README.md
Update SQL injection part :
- bqSQL
- example with implode on strings
Add Compliancy part regarding PS_VERSION declaration
> Update SQL Injection + Add Compliancy

- docs/src/10-validation-checklist/README.md
Organisation of the review page, addition of the security and best practices section
> Page rework

- docs/src/10-validation-checklist/README.md
Adding a note regarding syntax for automatic validation
> [IMP] Improve docs for automatic validation

- docs/src/7-prestashop-cloudsync/README.md
Update mandatories consents for CloudSync MSC
> Update mandatories consents for CloudSync MSC

- docs/src/1-how-it-works/README.md
> Adding CloudSync MSC light component in the doc

- docs/src/7-prestashop-cloudsync/README.md
Adding news CloudSync consents that are now available.
> Updating CloudSync consents

- docs/src/10-validation-checklist/README.md
Add rules regarding external links and obfuscated code that wasn't documented yet
> Update validation rules
